Team-Piglin/swapswap

src/main/java/piglin/swapswap/domain/member/entity/Member.java, src/main/java/piglin/swapswap/domain/post/constant/Category.java, src/main/java/piglin/swapswap/domain/post/entity/Post.java
- DB 테이블 생성 시 게시글 테이블 생성 오류가 생겨서 카테고리 enum 타입에 요소를 추가했습니다.
- 중요한 데이터인 Member, Post 에 명시적 삭제 컬럼이 존재 하지 않았습니다
<br>
- Category enum 클래스에 제품 타입별 분류하고 추가했습니다.
- Member, Post 에 명시적 삭제 컬럼을 추가 했습니다.
<br>
- 저장 시 값을 한글로 저장되게 했습니다 ! 영어로 할까 한글로 할까 고민했는데 한글로 하는 게 나을 거 같았습니다
<br>
=> Design: 게시글 카테고리 요소 추가 / Member, Post 명시적 삭제 컬럼 추가

src/main/java/piglin/swapswap/domain/coupon/entity/Coupon.java, src/main/java/piglin/swapswap/domain/membercoupon/entity/MemberCoupon.java
- 선착순 쿠폰 이벤트를 위한 Coupon 관련 테이블 구조 변경
<br>
- 기존 하나의 쿠폰 테이블만 가지고 있던 구조에서 아래 그림과 같이 변경
- 선착순 쿠폰 이벤트를 위해 쿠폰의 갯수를 필드로 가진 쿠폰 엔티티와
- 유저가 가지고 있는 쿠폰을 나타낼 수 있는 유저-쿠폰 엔티티로 구조 변경
<br>
- 첨부한 ERD와 엔티티 구현이 일치하는지를 중점으로 봐주시면 감사하겠습니다.
<br>
=> Feat: 선착순 쿠폰 이벤트를 위한 Coupon 관련 테이블 구조 변경 #33

src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java, src/main/java/piglin/swapswap/domain/coupon/dto/request/CouponCreateRequestDto.java, src/main/java/piglin/swapswap/domain/coupon/mapper/CouponMapper.java, src/main/java/piglin/swapswap/domain/coupon/repository/CouponRepository.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java, src/main/java/piglin/swapswap/domain/coupon/validator/CouponValidator.java, src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java, src/main/java/piglin/swapswap/global/exception/coupon/CouponExpiredTimeException.java, src/main/resources/static/style.css, src/main/resources/templates/coupon/createCouponForm.html
- 쿠폰을 생성하는 기능을 추가하였습니다.
<br>
- #8 해당 이슈를 참고하여 쿠폰 생성 기능을 구현하였습니다.
<br>
- 현재 User 파트가 완성되지 않아 관리자 검증은 완료하지 못한 상태입니다.
- 추후에 User 파트가 완성되면 검증 코드 추가와 검증 테스트를 추가할 것 입니다.
- 나중에 쿠폰 사용 시, 만료 기한이 지난 쿠폰 사용 검증을 추가하기 위해 `CouponValidator`를 생성하여 쿠폰에 대한 검증 클래스를 따로 두었습니다.
- 고민 했던 점은 나중에 어드민 검증이 추가되면 `createCoupon() `메서드에서 검증하는 코드만 2줄일텐데 이를 service 클래스에서 따로 validate 메서드를 생성해서 묶어서 처리할지 아니면 두 줄의 코드를 그대로 둘지 고민입니다.
<br>
=> Feat: 쿠폰 생성 기능 추가

src/main/java/piglin/swapswap/domain/post/controller/PostController.java, src/main/java/piglin/swapswap/domain/post/service/PostService.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java, src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
- [#40 ] 이슈에 관한 내용입니다.
- 간략하게 요약하면, DB 조회 한번만 해도 되는 걸 두번해야 되는 일이 생겼습니다.
<br>
- MemberId를 받는 부분을 Member로 받게 끔 진행했습니다.
- 이에 따른 테스트 코드 로직을 수정했습니다.
- 사용하지 않는 메소드는 제거했습니다.
<br>
- 아직 유저 인증 인가가 구현되지 않아, 구현 후 @AuthUser 어노테이션을 쓴다는 가정하에 코드를 적었습니다.
- 테스트 코드 통과 및 직접 테스트 했을 때도 문제 없었습니다.
<br>
=> refactor: createPost 매개변수 MemberId -> Member 변경

src/main/java/piglin/swapswap/domain/post/controller/PostController.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java, src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java, src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
- [#49 ] 에 관한 내용입니다.
- 로그인 안 한 사용자가 게시글을 작성할 수 있던 오류가 있었습니다.
<br>
- 시큐리티에 posts/write 추가했습니다
- 더블 체킹 할 수 있도로 서비스, 컨트롤러 단에서도 예외를 발생하게 작성했습니다.
<br>
- 우선 get은 리다이렉트, post는 커스텀 예외를 발생하게 했는데, 이게 맞을지 모르겠습니다.. 시큐리티가 정상 작동해서 애초부터 막을 수 있게하면 막을 수 있는데, 혹시 몰라서 더블 체킹으로 해놨습니다.
<br>
=> bugfix: 로그인 안 한 사용자가 게시글을 작성할 수 있는 오류 수정

src/main/java/piglin/swapswap/domain/post/controller/PostController.java, src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java, src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java, src/main/java/piglin/swapswap/domain/post/service/PostService.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java, src/main/resources/templates/post/postList.html
- 기존 로직은 Map<Long, ResponseDto> 로 Key에는 postId 가 들어가게 했습니다.
- 하지만 곰곰히 생각해보니 맵 형식으로 굳이 반환하지 말고 Page로 반환하는 거랑 별반 차이를 못느꼈습니다.
- 추후 개발 될 거래 기능에서도 MemberId와 PostId가 필요하여 Map -> Page 로 바꾸었습니다.
<br>
- Map -> Page 반환 타입 수정
- PostId 및 MemberId 추가 반환
- html 타임리프 수정
<br>
- 작명을 좀 이쁘게 못 한 거 같습니다. 이름 추천해주세요
- 기존 html에서 로직적으로는 많이 바뀌지는 않았지만, postList에 관해 작성하시던 코드가 있으시면 제 코드 보시고 바꾸셔야 합니다.
<br>
=> feat: getPostList 반환 Page로 반환 하게 수정

src/main/java/piglin/swapswap/domain/post/controller/PostController.java, src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java, src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java, src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java, src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java, src/main/resources/templates/post/postList.html
- [#73 ]
- [#74 ] 
- 에 관한 내용입니다.
<br>
- 기존 Spring Data Jpa 에서 QueryDsl로 바꾸어 N+1 방지 쿼리를 새로 작성하였습니다.
- select 절 서브쿼리를 이용해 로그인 한 사용자의 게시글 좋아요 상태를 확인 할 수 있습니다.
포스트 10개 기준 수정 전 지연 시간 86ms에서 수정 후 33ms로 지연 시간이 61.63% 나 줄었습니다
<br>
- 꼼꼼히 봐주십쇼 감사합니다 🥲
<br>
=> refactor: 커서 기반 페이지네이션을 위한 N+1 방지 두방 쿼리 리팩토링

src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java, src/main/java/piglin/swapswap/domain/coupon/dto/response/CouponGetResponseDto.java, src/main/java/piglin/swapswap/domain/coupon/mapper/CouponMapper.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java, src/main/resources/templates/coupon/couponDetail.html
- #82 
- 쿠폰을 생성하여 옮겨지거나 url을 직접 입력하여 볼 수 있는 쿠폰 상세 페이지입니다.
<br>
- /coupons/{couponId} URL을 입력하면 해당 쿠폰을 DB에서 조회하여 화면에 출력
<br>
- 쿠폰 CRUD는 관리자의 권한이 필요한 기능이기 때문에 쿠폰 발급과 controller를 분리할 계획입니다.
<br>
=> Feat: 쿠폰 상세 페이지 및 기능 구현

src/main/java/piglin/swapswap/domain/coupon/controller/AdminCouponController.java, src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java, src/main/java/piglin/swapswap/domain/member/constant/MemberRole.java, src/main/java/piglin/swapswap/domain/member/constant/MemberRoleEnum.java, src/main/java/piglin/swapswap/domain/member/entity/Member.java, src/main/java/piglin/swapswap/domain/member/mapper/MemberMapper.java, src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java, src/main/java/piglin/swapswap/global/jwt/JwtUtil.java, src/main/java/piglin/swapswap/global/security/UserDetailsImpl.java, src/main/resources/templates/coupon/createCouponForm.html, src/main/resources/templates/coupon/issueEventCoupon.html, src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java
쿠폰을 CRUD할 수 있는 권한을 어드민으로 제한
- 쿠폰 CRUD 권한 어드민으로 제한
<br>
- 쿠폰 CRUD를 위한 어드민 전용 컨트롤러와 쿠폰 발급을 위한 일반 유저용 컨트롤러로 구분하였습니다.
- 쿠폰 CRUD의 권한을 어드민으로 제한하였습니다.
- MemberRoleEnum의 필드 값을 각각 ROLE_USER -> USER, ROLE_ADMIN -> ADMIN으로 변경하였습니다.
<br>
- 컨트롤러단에서 권한 제한을 할 수 있지만 권한 제한에 대한 내용을 한 곳에서 볼 수 있게 하기 위해 WebSecurityConfig에 선언하였습니다.
<br>
=> Refactor: 쿠폰 CRUD 권한을 어드민으로 제한

src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java, src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java, src/main/resources/templates/post/postList.html, src/main/resources/templates/post/postListFragment.html, src/main/resources/templates/post/postSearchList.html
- 기존 QueryDsl 에서 Projections.fileds 방법이랑.. @QueryProjection 등만 있는 것만 기억났었는데 게시글 단건 조회에서 constructor 방법 있는 거 기억나서 다시 수정했습니다!
<br>
- 게시글 리스트 조회 매핑방식 fields -> constructor / 이에 따른 PostGetListResponseDto record 클래스로 재 수정 / alias 삭제
<br>
- 수정한 부분 많이 없고, 실수한 부분있을 수 있으니 쬐끔 자세히 봐주세요~~
<br>
=> refactor: 게시글 리스트 조회 매핑방식 fields -> constructor

src/main/java/piglin/swapswap/domain/member/repository/MemberQueryRepository.java, src/main/java/piglin/swapswap/domain/member/repository/MemberQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java, src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java, src/main/java/piglin/swapswap/domain/member/service/MemberService.java, src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java, src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java, src/main/java/piglin/swapswap/domain/wallet/dto/request/DepositSwapMoneyRequestDto.java, src/main/java/piglin/swapswap/domain/wallet/entity/Wallet.java, src/main/java/piglin/swapswap/domain/wallet/service/WalletService.java, src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java, src/main/java/piglin/swapswap/domain/wallethistory/constant/HistoryType.java, src/main/java/piglin/swapswap/domain/wallethistory/entity/WalletHistory.java, src/main/java/piglin/swapswap/domain/wallethistory/mapper/WalletHistoryMapper.java, src/main/java/piglin/swapswap/domain/wallethistory/repository/WalletHistoryRepository.java, src/main/java/piglin/swapswap/domain/wallethistory/service/WalletHistoryService.java, src/main/java/piglin/swapswap/domain/wallethistory/service/WalletHistoryServiceImplV1.java, src/main/resources/static/css/style.css, src/main/resources/templates/wallet/depositSwapMoney.html
- 지갑에 스왑머니 입금 페이지와 기능을 구현하였습니다.
<br>
- 지갑을 가져오는 것은 멤버를 지갑과 페치조인하여 가져와 사용하였습니다.
- 지갑에 들어오는 모든 입출금 기록을 남기기 위해서 WalletHistory 테이블을 아래와 같이 변경하였습니다.
<br>
- 수수료를 지갑 기록에 넣으려고 했지만 그렇지 않았습니다. 지갑 기록에 넣기보단 거래 테이블에 수수료를 추가하는 것이 좋다고 생각하였기 때문입니다. 보통 거래내역에 수수료가 있지 입출금기록에는 총 금액만 담겨있기 떄문입니다.
<br>
=> Feature: 지갑 입금 페이지 및 기능 구현

src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java, src/main/java/piglin/swapswap/domain/wallet/service/WalletService.java, src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java, src/main/java/piglin/swapswap/domain/wallethistory/entity/WalletHistory.java, src/main/java/piglin/swapswap/domain/wallethistory/mapper/WalletHistoryMapper.java
- 거래 완료 시, 공용으로 사용하기 위해서 메서드를 공통화
<br>
- 거래 완료 시, 공용으로 사용하기 위해서 메서드를 공통화
- WalletHistory 엔티티 생성 시, 참조 값인 wallet을 누락해 추가
<br>
- 거래 완료 시, 사용하게 될 walletservice에 문제가 없는지 확인해주세요
<br>
=> Refactor: Service Layer의 입금/출금 메서드 공통화

src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
- 모든 채팅방이 보이는 버그 해결
<br>
- 채팅방 목록을 불러오는 쿼리 수정
**수정 전 코드**
```java
queryFactory
.select(Projections.constructor(ChatRoomResponseDto.class,
chatRoom.id,
member.nickname,
chatRoom.lastMessage,
chatRoom.lastMessageTime))
.from(chatRoomMember)
.join(chatRoom).on(chatRoomMember.chatRoom.id.eq(chatRoom.id))
.join(member).on(chatRoomMember.member.id.eq(member.id))
.where(chatRoomIdIn(memberId),memberIdNotEq(memberId))
.fetch();
```
**수정한 코드**
```java
queryFactory
.select(Projections.constructor(ChatRoomResponseDto.class,
chatRoom.id,
member.nickname,
chatRoom.lastMessage,
chatRoom.lastMessageTime))
.from(chatRoomMember)
.join(chatRoom).on(chatRoomMember.chatRoom.id.eq(chatRoom.id))
.join(member).on(chatRoomMember.member.id.eq(member.id))
.where(memberIdNotEq(memberId))
.fetch();
```
<br>
=> Fix: 모든 채팅방이 보이는 버그 해결

src/main/java/piglin/swapswap/domain/post/controller/PostController.java, src/main/resources/templates/post/post.html
- 게시글을 볼 때 작성자가 아닌데도 수정, 채팅, 삭제 버튼이 떠서 내 게시글인지, 남의 게시글인지 헷갈렸습니다.
<br>
- 작성자가 아닐 시 수정, 업, 삭제 버튼이 뜨지 않게 수정했습니다.
<br>
- 쓱 봐주세요!
- 자신의 게시글
- 타 유저의 게시글
<br>
=> feat: 작성자가 아닐 시 수정, 업, 삭제 버튼 안뜨게 수정

src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java, src/main/java/piglin/swapswap/domain/post/entity/Post.java, src/main/java/piglin/swapswap/domain/post/service/PostService.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java, src/main/resources/application-local.yml, src/main/resources/templates/post/post.html
- 거래 상태에 따른 포스트에 거래상태 표시 기능 구현
- #158 에 관한 내용 브랜치 명만 수정하여 다시 올렸습니다.
<br>
- 거래 요청 후 유저 모두 수락 시 거래 진행으로 표시, post의 거래 상태도 업데이트
- 거래 인수도 모두 인수 시 거래 완료로 표시 및 요청 상태가 아닌 deal에 대해서는 요청할 수 없게 요청하기 버튼 삭제
<br>
-  내용대로 동작은 정상으로 돌아갑니다. 하지만 postServiceImpl 부분에
return 쪽에 문제가 있을 것 같습니다. 그부분을 중점으로 봐주시면 감사하겠습니다.  
<br>
=> feat: 거래 상태에 따른 포스트에 거래상태 표시 기능 구현

src/main/java/piglin/swapswap/domain/member/constant/AnimalAdjective.java, src/main/java/piglin/swapswap/domain/member/constant/AnimalName.java, src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java, src/main/java/piglin/swapswap/domain/member/dto/MemberNicknameDto.java, src/main/java/piglin/swapswap/domain/member/entity/Member.java, src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java, src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java, src/main/java/piglin/swapswap/domain/member/service/MemberService.java, src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java, src/main/resources/templates/member/editProfile.html
- [#155]
- [#161]
- 유저 닉네임 + 숫자 4개로 구성되도록 수정 및 프론트에서 중복된 닉네임 검사
<br>
- 유저가 카카오로 로그인을 하여 db에 저장될 때 기존에는 닉네임에 실명이 들어가서 중복이 될 수 밖에 없는 상황이고 닉네임을 수정할 때는 중복이 되지 않는 상황이였는데 애초에 db에 저장될 때 실명 + 숫자 4개로 구성되게 하여 중복을 방지하였습니다
------
- 닉네임을 수정할 때 중복검사를 백엔드에서는 해줬지만 프론트에서 해주지 않아 중복됨에도 불구하고 정상적으로 변경되었다는 알림만 뜨고 실제로는 변경이 되지 않았는데 수정하였습니다.
------
<br>
- 비교적 간단한 코드라 스-윽 봐주시고 고칠 부분있으면 말씀해주세요
<br>
=> Fix: 유저 닉네임 + 숫자 4개로 구성되도록 수정 및 프론트에서 중복된 닉네임 검사

src/main/java/piglin/swapswap/domain/daelwallet/entity/DealWallet.java, src/main/java/piglin/swapswap/domain/daelwallet/mapper/DealWalletMapper.java, src/main/java/piglin/swapswap/domain/daelwallet/repository/DealWalletRepository.java, src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletService.java, src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java, src/main/java/piglin/swapswap/domain/deal/controller/DealController.java, src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java, src/main/java/piglin/swapswap/domain/deal/dto/request/DealUpdateRequestDto.java, src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java, src/main/java/piglin/swapswap/domain/deal/entity/Deal.java, src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java, src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/deal/service/DealService.java, src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java, src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java, src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java, src/main/resources/application-prod.yml, src/main/resources/static/css/style.css, src/main/resources/templates/deal/dealHistory.html, src/main/resources/templates/deal/dealRequestDeal.html, src/main/resources/templates/deal/dealRequestDealListForm.html, src/main/resources/templates/deal/dealResponseDealListForm.html, src/main/resources/templates/member/login.html
- 스왑 페이와 거래 연동 기능 구현
<br>
- DealWallet 테이블 추가 및 스왑머니 사용 여부에 따른거래 수락 시 지갑에서 스왑머니 출금 입금 기능 구현,  거래 인수 시 각 지갑에 DealWallet에 있던 금액을 입금합니다.
- 거래 수정 시 거래 수락 취소에 따른 DealWallet에 있는 돈을 원래 주인의 지갑으로 돌려주고 DealWallet 삭제합니다.
<br>
- 코드 컨벤션에 어긋나는 부분이나 오류 부분을  봐주셨으면 좋겠고 스왑페이 사용 부분을 중점으로 봐주시면 감사하겠습니다.
<br>
=> Feat:  스왑 페이와 거래 연동 기능 구현

src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
- 인수 시 dealWallet 있을 때만 withdrawMemberSwapMoneyAtComplete 메서드 실행 하도록 변경
<br>
- 인수 시 dealWallet 있을 때만 withdrawMemberSwapMoneyAtComplete 메서드 실행 하도록 변경
<br>
- fix 한 부분 만 봐주시면 감사하겠습니다.
<br>
=> fix: 인수 시 withdrawMemberSwapMoneyAtComplete 메서드 실행 조건 변경

src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java, src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java, src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
- 채팅방 마지막 메시지와 시간이 업데이트되지 않는 버그 해결
<br>
- @Transactional 누락으로 인한 변경감지 불가
- 이를 해결하기 위해 @Transactional 추가
<br>
=> Fix: 채팅방 마지막 메시지와 시간이 업데이트되지 않는 버그 해결

src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java, src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java, src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
- 거래 수락 파트 긴 코드 메서드화 및 쿼리 최적화
<br>
- 거래 수락 메서드가 if문이 많아 메서드로 추출해 메인 코드 부분을 줄였습니다.
- 여러 개의 게시물을 거래 진행 상태로 바꾸는 쿼리에서 조회 n개 쿼리 + 업데이트 n개 쿼리를 
- querydsl을 이용한 하나의 동적 쿼리로 해결하였습니다.
<br>
- 기존의 코드를 메서드로 추출해 메인 코드 메서드의 줄 수를 줄였습니다. 테스트 결과 정상적으로 나옵니다.
<br>
=> Refactor: 거래 수락 파트 긴 코드 메서드화 및 쿼리 최적화

src/main/resources/templates/member/myPostList.html, src/main/resources/templates/post/post.html, src/main/resources/templates/post/postFavoriteList.html, src/main/resources/templates/post/postList.html, src/main/resources/templates/post/postListFragment.html, src/main/resources/templates/post/postSearchList.html
- 기존 프론트에서 isoi8601 로 표기 되던 것이 불필요한 정보까지 사용자에게 알려주는 거 같았습니다.
<br>
- 프론트에서 날짜 표시 방법을 수정했습니다
<br>
- 사진에 올라와 있는 게 다입니다~~ 쓱 봐주세요
<br>
=> style: 게시글 단 건 및 목록 조회 시 올린 날짜 표시 방법 수정

src/main/java/piglin/swapswap/SwapswapApplication.java
- Docker에서 TimeZone 설정을 하여 Spring 자체에선 TimeZone 설정이 불필요해졌습니다.
<br>
- Application TimeZone 설정 제거
<br>
- 바로 머지하겠습니다!
<br>
=> fix: TimeZone 설정 제거

src/main/resources/static/css/style.css, src/main/resources/templates/post/post.html
- 게시글 단 건 조회 시 DealStatus 사진 뒤에 가려지던 오류 해결
<br>
- 게시글 단 건 조회 시 DealStatus 에 따라 사진 색 변경
- 게시글 거래 상태 이미지 뒤에 가려지던 오류 해결
<br>
- 바로 머지하겠습니다.
<br>
=> fix: 게시글 단 건 조회 시 DealStatus 사진 뒤에 가려지던 오류 해결

src/main/resources/templates/post/post.html
- 게시글 단 건 조회 시 게시글 완료 상태이고, 사진이 여러개면 DealStatus가 되게 이상하게 떴었습니다.
<br>
- 게시글 단 건 조회 시 DealStatus 사진 여러개면 엄청 길게 뜨는 오류 해결
- 
여기에서
이렇게 바꼈습니다.
<br>
- 바로 머지하겠습니다~
<br>
=> fix: 게시글 단 건 조회 시 DealStatus 사진 여러개면 엄청 길게 뜨는 오류 해결

src/main/java/piglin/swapswap/domain/chatroom_member/mapper/ChatRoomMemberMapper.java
- ChatRoomMember isDeleted 필드 추가로 인한 버그 해결
<br>
- 채팅 방 생성 시, ChatRoomMember엔티티를 만들 때,  ChatRoomMemberMapper에서 isDeleted 누락으로 인한 DB의 null 예외 발생
<br>
=> HOTFIX: ChatRoomMember isDeleted 필드 추가로 인한 버그 해결

src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java, src/main/java/piglin/swapswap/domain/chatroom/dto/ChatRoomResponseDto.java, src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java, src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java, src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepository.java, src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomRepository.java, src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomService.java, src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java, src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java, src/main/java/piglin/swapswap/domain/member/service/MemberService.java, src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java, src/main/java/piglin/swapswap/domain/message/dto/request/MessageRequestDto.java, src/main/java/piglin/swapswap/domain/message/dto/response/MessageResponseDto.java, src/main/java/piglin/swapswap/domain/message/entity/Message.java, src/main/java/piglin/swapswap/domain/message/mapper/MessageMapper.java, src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepository.java, src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/message/repository/MessageRepository.java, src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java, src/main/java/piglin/swapswap/global/security/UserDetailsImpl.java, src/main/resources/templates/chat/chatroom.html, src/main/resources/templates/chat/chatroomList.html, src/main/resources/templates/member/login.html, src/main/resources/templates/post/post.html
- 엔티티간에 연관관계를 가지지 않는 방향으로 재설계 하였습니다.
- ChatRoomMember 클래스는 더 이상 사용하지 않습니다.
<br>
- ChatRoom과 Message가 Member와 갖고 있던 연관관계를 제거하고 String 값이나 Long 값으로 id, nickname 값을 가지고 있도록 하였습니다.
- 채팅방 목록을 가져오는 메소드를 QueryDSL을 사용하여 작성하였지만 제대로 작동하지 않아 기존과 다르게 작성하였습니다.
- ChatRoomMember 클래스는 더 이상 사용하지 않습니다만 아직 삭제하지는 않았습니다.
- UserDetailsImpl에 회원의 id를 반환 받는 메소드를 작성하였습니다.
- 추가
- ChatRoom 엔티티에 isLeaveFirstMember, isLeaveSecondMember 필드를 추가해서 채팅방에서 회원이 나갈 시 null 값으로 만들지 않고 해당 필드를 true로 바꾸어 채팅방을 나간 후에도 해당 채팅방에 참여한 회원을 알 수 있도록 하였습니다.
- RequestParam으로 값을 받고 있던 부분을 제거하였습니다.
<br>
- ChatRoomServierImpl.class에 getChatRoomResponseDtoList 메소드가 채팅방 목록을 가져오는 메소드 입니다.
- 좋은 코드인 것 같지는 않아서 더 좋은 방법이 있다면 알려주시면 감사하겠습니다. 
<br>
=> Refactor: 엔티티간 연관관계를 가능한 가지지 않는 방향으로 리팩토링

src/main/java/piglin/swapswap/domain/post/constant/Province.java, src/main/resources/templates/common/fragments/nav.html
- [#229 ] 에 관한 내용입니다.
<br>
- post city 검색 바로 적용되게 수정 / Province 오타 수정
<br>
- 코드는 정말 별거 없는데,,, 그 이유가 js로 도, 도시 나눠놓고 경기도 선택하면 경기도 도시들 쫙 나오면서 도시 선택하고 기존 처럼 검색 되게 끔 하려고 했는데 적용이 계속 안되더라구요,, 하나하면 하나 이상해지고,, 이상적으로 작동이 안됩니다. 그래서 코드 3번 갈아 엎었었는데 프론트에서 로컬 스토리지 사용하고 이런 부분들이 꽤나 어려워서 포기하고 다른 부분에 집중하려고 우선 UT 개선 사항 올립니다..
- 쓱 봐주세요 ㅠ
<br>
=> feat: post city 검색 바로 적용되게 수정 / Province 오타 수정

src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
- deletePost 메서드에 대한 테스트 코드가 없었습니다.
<br>
- 게시글 삭제 테스트 코드 추가했습니다.
<br>
- 스케줄러 테스트 코드도 추가하려 했는데, 현재 게시글 완전 삭제되는 로직은 다른 방식으로 바뀔 예정이라 추가하지 않았습니다.
<br>
=> test: 게시글 삭제 테스트 추가

src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java, src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java, src/main/java/piglin/swapswap/domain/post/controller/PostController.java, src/main/java/piglin/swapswap/global/annotation/HttpRequestLog.java, src/main/java/piglin/swapswap/global/aspect/LogAspect.java
- [#244] 에 관한 내용입니다.
- 기존에는 Service 레이어 메소드에 @SwapLog 부착하고 HttpServletRequest를 받았습니다.
- 여기서 문제점이 통합 테스트를 실행할 때는 실질적으로 Controller 를 타고 요청이 오는 것이 아니라 HttpRequest가 없다는 것입니다.
- 통합 테스트 메서드 실행 -> 메서드에서 @SwapLog AOP 실행 -> HttpServletRequest로 로그 찍으려함 -> HttpServletRequest가 없음 -> 오류
<br>
- HttpRequestLog 어노테이션을 만들고 기존 SwapLog 어노테이션 AOP에 있는 HttpRequest 관련된 코드들을 새로운 AOP로 분리해주었습니다.
<br>
- 다른 더 좋은 방법이 있을까요? 하하
<br>
=> feat: Log HttpRequestLog / SwapLog 분리

src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
- 닉네임 수정이 되지 않던 버그 수정
<br>
- 변경감지가 일어나지 않아 @Transactional이 걸려있어도 닉네임이 수정되지 않았는데 isNotInTransactionMember라는 member를 만들어서 해결하였습니다
<br>
- 네
<br>
=> Fix : 닉네임 수정이 되지 않던 버그 수정

build.gradle, src/main/java/piglin/swapswap/domain/billcoupon/mapper/BillCouponMapper.java, src/main/java/piglin/swapswap/domain/billcoupon/repository/BillCouponQueryRepository.java, src/main/java/piglin/swapswap/domain/billcoupon/repository/BillCouponQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/billcoupon/service/BillCouponServiceImplV1.java, src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV2.java, src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV3.java, src/main/java/piglin/swapswap/domain/membercoupon/entity/MemberCoupon.java, src/main/java/piglin/swapswap/domain/membercoupon/mapper/MemberCouponMapper.java, src/main/java/piglin/swapswap/domain/membercoupon/repository/MemberCouponQueryRepository.java, src/main/java/piglin/swapswap/domain/membercoupon/repository/MemberCouponQueryRepositoryImpl.java, src/main/java/piglin/swapswap/domain/membercoupon/repository/MemberCouponRepository.java, src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponService.java, src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponServiceImplV1.java, src/main/java/piglin/swapswap/global/config/RedisConfig.java, src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java, src/main/java/piglin/swapswap/global/exception/membercoupon/MemberCouponNotFoundException.java, src/main/java/piglin/swapswap/global/scheduler/Scheduler.java, src/main/resources/application-local.yml, src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java, src/test/resources/application.yml
- 레디스를 이용해 선착순 쿠폰 발급 성능 향상
<br>
- 쿠폰 - 멤버 쿠폰 연관관계 형성
- CouponService V1(낙관적 락) -> V2(비관적 락) -> V3(레디스)로 분리
- 레디스의 INCR 메서드를 이용해 선착순 쿠폰 발급 성능 향상
- 두 지표, 모두 JVM의 Warm-up Time을 고려해 2번 이상 테스트를 진행하였습니다. 지금 표로 보아선 TPS는 차이가 크게 없어보이고, MTT에 대해서 레디스가 훨씬 우수하여 전체 테스트 시간 또한 짧은 것을 볼 수 있습니다. 더 자세한 분석은 추후에 진행하여 작성하도록 하겠습니다.
- 기존 비관적 락
-레디스로 교체 후
<br>
- 생각보다 DB 락도 빠르다는 것을 알게된 계기가 된 것 같습니다.
<br>
=> Feat: 레디스를 이용해 선착순 쿠폰 발급 성능 향상

src/main/java/piglin/swapswap/global/scheduler/Scheduler.java
- 기존 테이블에서 V2 테이블로 업데이트하면서 탈퇴하더라도 연관관계를 끊지 않는 식으로 결정했습니다.
- 추후 고객 중요정보는 Null 값으로 바꾸는 로직을 넣을 것이나, 현재는 배포를 우선적으로 하기 위해 기존 로직들 주석처리하였습니다.
<br>
- delete Scheduler 한시적 미사용 변경
<br>
- 쓱 봐주세요~
<br>
=> feat: delete Scheduler 한시적 미사용 변경

src/main/resources/templates/post/post.html
- 변수명이 달라 Controller에서 파라미터를 받지 못하던 부분을 수정했습니다
<br>
- post.html에서 변수명 변경 : receiveMemberId -> secondMemberId<br>
- 리뷰어에게 중점적으로 봐줬으면 하는 부분을 입력하세요.
<br>
=> Fix: 변수명이 달라 Controller에서 파라미터를 받지 못하던 부분 해결

src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
- 게시글 검색 시 띄어쓰기가 일치해도 검색이 안됐습니다.
<br>
- param으로 들어온 내용의 띄어쓰기를 안 빼줘서 생기는 오류였습니다.
- param으로 받은 문자열의 공백을 제거해주는 로직을 추가했습니다.
<br>
- 쓱 봐주세요!
<br>
=> fix: 게시글 검색 띄어쓰기 일치해도 검색 안되는 오류 수정

src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java, src/main/java/piglin/swapswap/domain/member/dto/OtherMemberInfoDto.java, src/main/java/piglin/swapswap/domain/member/mapper/MemberMapper.java, src/main/java/piglin/swapswap/domain/member/service/MemberService.java, src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java, src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java, src/main/java/piglin/swapswap/domain/post/service/PostService.java, src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java, src/main/resources/templates/member/otherMemberInfo.html
- 멤버 프로필 조회 후 게시글 더 불러올 시 다른 게시글이 불러오는 오류가 있었습니다.
<br>
- 멤버 프로필 게시글 조회 다른 멤버 게시글 불러오는 문제 해결
<br>
- 현재 이 기능에서 게시글 찜 확인을 param에 들어간 memberId 기준으로 조회해서 제대로 확인이 안되는 오류가 있습니다.
- 그 부분 수정하고 추가로 올리겠습니다
<br>
=> fix: 멤버 프로필 게시글 조회 다른 멤버 게시글 불러오는 문제 해결

src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
- [#282 ]
<br>
- 파람으로 들어온 title replace 하는 부분에서 NullPointException 뜨는 것으로 확인
- 해당 부분 null 이 아닐때 컨디션 설정하는 것으로 바꿨습니다.
<br>
- 허허... 이 실수를 이제야 발견했네요
<br>
=> fix: 메인페이지 카테고리 및 도시 선택 시 302 오류 해결
