Team-Piglin/swapswap

src/main/java/piglin/swapswap/domain/member/constant/MemberRoleEnum.java
src/main/java/piglin/swapswap/global/jwt/JwtAuthenticationFilter.java
src/main/java/piglin/swapswap/global/jwt/JwtAuthorizationFilter.java
src/main/java/piglin/swapswap/global/jwt/JwtUtil.java
src/main/resources/application.yml

- jwt관련 코드입니다
<br>
- jwt관련 코드입니다
<br>
- jwt관련 코드입니다
<br>

Feat : JWT 

---

src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java

- wallet부분 수정
<br>
- wallet부분 수정
<br>
- wallet부분 수정
<br>

Feat: wallet부분 수정

---

src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/test/java/piglin/swapswap/domain/favorite/service/FavoriteServiceImplV1UnitTest.java
src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java

- favoriteServiceImplV1 테스트 코드입니다.
<br>
- 간단한 서비스 단위 테스트 코드를 작성했습니다.
<br>
- 아주 간단한 거니 훑어보시면 됩니다~~
<br>

test: favoriteServiceImplV1 테스트 코드 작성

---

src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/java/piglin/swapswap/domain/post/dto/request/PostUpdateRequestDto.java
src/main/java/piglin/swapswap/domain/post/entity/Post.java
src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/java/piglin/swapswap/global/s3/S3ImageService.java
src/main/java/piglin/swapswap/global/s3/S3ImageServiceImplV1.java
src/main/resources/application.yml
src/main/resources/static/css/style.css
src/main/resources/templates/post/post.html
src/main/resources/templates/post/postUpdateWrite.html
src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java

- [#58 ] 에 관한 내용입니다.
- 게시글 수정 기능이 필요했습니다
<br>
- 게시글 수정 기능 추가
- 자신의 게시글만 수정할 수 있게 예외처리
- html 수정하기 버튼 추가
- 테스트 코드 추가
<br>
- 시큐리티 부분은 추후에 정리를 하는 게 좋을 거 같습니다.
- 우선 write 들어갈 때 로그인 안되어 있으면 튕겨내게 해놨는데, 이것들은 시큐리티 재정리 후에 다 빼야될 거 같습니다
<br>

feat: 게시글 수정 기능 추가

---

src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/java/piglin/swapswap/domain/post/entity/Post.java
src/main/java/piglin/swapswap/domain/post/event/DeleteImageUrlEvent.java
src/main/java/piglin/swapswap/domain/post/event/ImageEventListener.java
src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/java/piglin/swapswap/global/s3/S3ImageServiceImplV1.java
src/main/resources/static/css/style.css
src/main/resources/templates/post/post.html
src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java

- [#60 ] 에 관한 내용입니다.
- -------------------------------------
- 2024-01-13
- [https://github.com/Team-Piglin/swapswap/issues/62] 에 관한 커밋 추가 됐습니다!!
<br>
- 게시글 삭제 기능추가
- html 삭제 버튼 추가
- 삭제 시 홈으로 리다이렉트
<br>
- 간단한 코드이니 간단하게 봐주세요
- 추후에 스케줄러로 삭제된지 n일이 지난 기능 추가할 예정입니다.
<br>

feat: 게시글 삭제 기능 추가

---

src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
src/main/resources/static/css/style.css
src/main/resources/templates/post/postList.html
src/main/resources/templates/post/postListFragment.html
src/main/resources/templates/post/postSearchList.html

- [#71 ] 에 관한 내용입니다.
<br>
- modifiedUpTime 기준 커서 기반 페이지네이션 기능 추가
- Pageable 삭제
- html css js 기능 추가
- 검색 전용 html 폼 분리
- 검색 기능에도 커서 기반 페이지네이션 기능 추가
<br>
- 개요에 태그한 이슈 꼭 읽어주세요!
- 커서 기반 페이지네이션 구현할 때 기준이 Unique 해야하는데, 검색 기준이 시간에 ms 까지 따져서 엄청 예외적인 부분이라 Unique 처리하지 않았습니다.
<br>

feat: 커서 기반 페이지네이션 기능 추가

---

src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
src/main/resources/templates/coupon/couponDetail.html
src/main/resources/templates/coupon/issueEventCoupon.html

- 쿠폰 Id와 이름이 바뀌어 출력되는 버그를 수정하였습니다.
- 잘못된 url로 쿠폰 요청하는 버그를 수정하였습니다.
<br>
- Id와 이름을 바꾸어 출력
- 잘못된 url로의 쿠폰 요청을 수정
<br>
- 실수해서 죄송합니다^^;
<br>

Fix: 쿠폰 Id, 이름 출력 오류 수정

---

src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/resources/static/css/style.css
src/main/resources/templates/common/fragments/nav.html
src/main/resources/templates/member/myPage.html
src/main/resources/templates/post/postFavoriteList.html

- [#97 ] 에 관한 내용입니다.
<br>
- 내가 찜한 게시글 목록을 확인하는 기능을 추가했습니다.
- queryDsl 서브 쿼리
- 찜 목록 확인용 html 생성
- 찜 목록도 커서 기반 페이지네이션 적용했습니다
<br>
- 꼼꼼히 봐주십쇼!!
<br>

feat: 내 찜 목록 확인 기능 추가

---

src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java
src/main/java/piglin/swapswap/domain/wallet/dto/request/WithdrawSwapMoneyRequestDto.java
src/main/java/piglin/swapswap/domain/wallet/entity/Wallet.java
src/main/java/piglin/swapswap/domain/wallet/service/WalletService.java
src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java
src/main/java/piglin/swapswap/domain/wallethistory/constant/HistoryType.java
src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
src/main/java/piglin/swapswap/global/exception/wallet/InvalidWithdrawException.java
src/main/resources/static/css/style.css
src/main/resources/templates/coupon/issueEventCoupon.html
src/main/resources/templates/member/mySwapMoney.html
src/main/resources/templates/wallet/depositSwapMoney.html
src/main/resources/templates/wallet/withdrawSwapMoney.html

- 지갑에 들어있는 스왑머니를 출금하는 페이지와 기능 구현하였습니다.
<br>
- 지갑에 들어있는 스왑머니를 출금하는 페이지를 구현하였습니다.
- 지갑에 들어있는 스왑머니를 출금하는 기능을 구현하였습니다.
- 지갑에 있는 돈이 출금하려는 돈보다 적으면 예외가 발생하게 하였습니다.
<br>
- 로직의 모순이 되는게 없나 확인해 주시면 감사하겠습니다.
<br>

Feature: 지갑 출금 페이지 및 기능 구현

---

src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java

- [#103 ] 에 관한 내용입니다.
<br>
- 어제 PR과 마찬가지로 More 메소드를 분리하였습니다.
<br>
- 빠르게 머지하겠습니다!.
<br>

fix: 찜 목록 게시글 아예 없을 때 예외 반환하는 오류 수정

---

src/main/java/piglin/swapswap/SwapswapApplication.java

- 개요를 입력하세요.
<br>
- 작업 내용을 입력하세요.
<br>
- 리뷰어에게 중점적으로 봐줬으면 하는 부분을 입력하세요.
<br>

test: ci/cd

---

src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
src/main/java/piglin/swapswap/domain/deal/service/DealService.java
src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
src/main/resources/static/css/style.css
src/main/resources/templates/deal/dealRequestDeal.html

- 거래 수락, 거래 인수 기능 구현 
<br>
- 거래 상세 조회 페이지에서 거래 수락, 거래 인수 여부를 선택 가능 하게 만들었습니다.
<br>
-  코드에서 오류부분이나 컨벤션에 맞지 않는 코드가 있으면(개선 사항) 코멘트 달아주시면 감사하겠습니다.
<br>

Feat : 거래 수락, 거래 인수 기능 구현 

---

src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java

- Wallet 필드 변경에 따른 테스트 코드 수정
<br>
- Wallet 엔티티의 money 필드의 이름이 swapMoney로 변경
- softDelte를 위한 isDeleted 필드 추가로 인한 테스트 코드 수정.
<br>
- 테스트 코드 약간 수정하였습니다~
<br>

fix: Wallet 필드 변경에 따른 테스트 코드 수정

---

src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java
src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java

- 이번에 추가한 게시글 지역기능으로 테스트코드가 동작하지 않아서 수정하고 올렸습니다.
<br>
- 테스트 코드 수정
<br>
- 바로 머지 하겠습니다
<br>

test: 테스트 코드 오류 수정

---

src/main/resources/templates/common/fragments/nav.html

- 게시글 등록시 cityInput 란의 id와 nav의 cityInput 의 id가 겹쳐서 게시글이 등록이 안되는 오류가 있었습니다. 
<br>
- 네비게이션 id cityInput -> navCityInput으로 수정
<br>
- 버그여서 바로 머지하겠습니다
<br>

fix: 게시글 등록 오류 수정

---

src/test/resources/application.yml

- CI를 위한 test DB 변경
<br>
- test DB를 MYSQL -> H2로 변경
<br>

Modify: test DB 변경

---

src/test/resources/application.yml

- test 빌드를 위해 환경 변수 값도 암호화 진행
<br>
- test 빌드를 위해 환경 변수 값도 암호화 진행
<br>

Modify:  test 빌드를 위해 환경 변수 값도 암호화 진행

---

src/main/resources/templates/common/fragments/nav.html
src/test/resources/application.yml

Swapswap Ver.1.0.1 배포

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Swapswap Ver.1.0.2 배포

---

Dockerfile
src/main/resources/application.yml

Swapswap Ver.1.0.3 배포

---

src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/templates/member/login.html
src/test/resources/application.yml

- 배포를 위한 kakao redirect url 변경
<br>
- 배포를 위한 kakao redirect url 변경
<br>

Fix: 배포를 위한 kakao redirect url 변경

---

src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/templates/common/fragments/nav.html
src/main/resources/templates/member/login.html
src/test/resources/application.yml

Swapswap Ver.1.0.4 배포

---

src/main/java/piglin/swapswap/domain/member/contorller/MainMvcController.java
src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java

- 템플릿을 찾지 못하는 오류 발생 해결
- #137 
<br>
- Controller에서 반환하는 url을 변경
ex) "/member/coupon" -> "member/coupon
<br>

Fix: Thymleaf 템플릿 오류

---

src/main/resources/templates/post/post.html

- Thymleaf memberId 오류 수정
<br>
- Thymleaf memberId 오류 수정
- userId() -> memberId
<br>

Fix: Thymleaf memberId 오류 수정

---

src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
src/main/resources/templates/post/post.html

- Swapswap Ver.1.0.7 배포
<br>
- 모든 채팅방이 보이는 버그 해결
<br>

Swapswap Ver.1.0.7 배포

---

src/main/resources/application-prod.yml
src/main/resources/static/css/style.css
src/main/resources/templates/post/postUpdateWrite.html
src/main/resources/templates/post/postWrite.html

- 이미지 업로드 용량 제한을 늘려서 사용자에게 알려주기 위한 글을 추가했습니다.
<br>
- 이미지 최소 최대 문구 추가
<br>
- 쓱 봐주세요~~
<br>

doc: 이미지 최소 최대 문구 추가

---

src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java

- 테스트 코드를 확인 못했습니다... 확인 잘 하겠습니다!
<br>
- nullResponse null 값 추가
<br>

fix: Test 수정

---

src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/java/piglin/swapswap/domain/post/entity/Post.java
src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/resources/static/css/style.css
src/main/resources/templates/member/login.html
src/main/resources/templates/member/myPage.html
src/main/resources/templates/member/myPostList.html
src/main/resources/templates/post/post.html
src/main/resources/templates/post/postFavoriteList.html
src/main/resources/templates/post/postList.html
src/main/resources/templates/post/postListFragment.html
src/main/resources/templates/post/postSearchList.html

- [#153] 에 관한 내용입니다.
<br>
- 내가 작성한 게시글 목록 확인
- 커서 기반 페이지네이션 적용
- 타임리프 모델 카멜케이스로 수정
- css 클래스 겹친 것 수정
<br>
- 꼼꼼히 봐주세요~
<br>

feat: 내가 작성한 게시글 목록 확인

---

src/main/resources/templates/member/login.html

- 로컬 환경 테스트할 때 callback 을 바꿔놨었는데.. 롤백을 하지 않고 푸시를 했었습니다...
<br>
- login.html call back 수정
<br>
- 바로 머지하겠습니다!
<br>

fix: login.html call back 수정

---

src/main/resources/static/css/style.css
src/main/resources/templates/post/post.html

- 게시글 단 건 조회에서 사용자 경험이 나빠질 만한 요소들이 있었습니다.
- ex. 자신 게시글을 조회 하는데 채팅하기 버튼이 보이고, 호버 효과가 동작하지 않아서 이 기능이 진짜 동작하는지 모르는 등
- 내일있을 유저 테스트를 위해서 사용자 경험을 높이기 위해 조금 더 이쁘게 만들었습니다!!
<br>
- 자신의 게시글 조회 시 채팅하기 버튼 안보이게 수정
- 게시글 버튼 스타일 정리 및 호버 추가
- 게시글 단 건 조회 스타일 수정
- 게시글 Up, Delete 버튼 Confirm
- 자신의 게시글 조회 시 요청하기 버튼 안 뜨게 수정
<br>
- html 부분이라 쓰윽 봐주십쇼!
<br>

feat:  자신의 게시글 조회 시 채팅하기 버튼 안보이게 / 게시글 단건 조회 스타일 수정

---

src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
src/main/java/piglin/swapswap/domain/message/service/MessageService.java
src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java

- 메서드 표기법을 변경했습니다.
<br>
- 메서드 표기법을 변경했습니다.
<br>
- 메서드 이름만 수정했습니다.
<br>

Refactor: findAllByChatRoom_Id -> findAllByChatRoomId 메서드 표기법 변경

---

src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/resources/templates/post/postWrite.html

- 게시글 등록 버튼 연타 시 연속으로 게시글이 등록되던 문제가 있었습니다.
<br>
- 게시글 등록 버튼을 누를 시 confirm 창을 띄워 연타를 하지 못하도록 방지했습니다.
<br>
- html 적인 부분이니 쓱 봐주세요!
<br>

fix: 게시글 등록 버튼 연타 시 계속 등록되던 상황 해결

---

src/main/java/piglin/swapswap/domain/chatroom/controller/StompController.java
src/main/resources/static/css/style.css
src/main/resources/templates/chat/chatroom.html

- 내가 보낸 메시지와 받은 메시지를 구분하기 쉽도록 좌우로 구분하였습니다.
<br>
- 내가 보낸 메시지와 받은 메시지를 구분하기 쉽도록 좌우로 구분하였습니다.
- 기존 메시지 내역도 좌우로 나누어 받아올 수 있도록 하였습니다.
<br>
- 슥 한번 훑어봐주시면 될 것 같습니다.
<br>

Feature: 보낸 메시지, 받은 메시지 좌우 구분 기능 추가

---

src/main/resources/static/css/style.css

- 글 내용 조회시 개행을 해서 작성했는데 단 건 조회 시 개행이 적용이 안됐던 버그가 있었습니다.
<br>
- DB에는 개행(\n) 이 잘 적용되는 것으로 보아 html 문제인걸로 판단하여 white-space: pre-line 를 글 본문에 추가했습니다.
<br>
- 한 줄 밖에 추가 안했습니다!! 바로 머지하겠습니다.
<br>

style: 게시글 단 건 조회 글 내용 개행 적용

---

src/main/resources/templates/common/fragments/nav.html
src/main/resources/templates/post/postUpdateWrite.html
src/main/resources/templates/post/postWrite.html

- [#183]  
- [#185 ]
- [#186 ] 에 관한 내용입니다.
<br>
- 경상북도 안동시 오기입 / 충청남도 공주시 누락 수정
- nav 채팅방 로그인 시 뜨게 설정 및 고객센터 미구현 alert
- 게시글 등록 시 Valid Alert 우선순위 개선
<br>
- 직접 기입하다보니 실수가 있었습니다 ! 쓰윽 봐주세요~
<br>

fix: 경상북도 안동시 오기입 / 충청남도 공주시 누락 수정

---

src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/resources/static/css/style.css
src/main/resources/templates/member/myPostList.html
src/main/resources/templates/post/post.html
src/main/resources/templates/post/postFavoriteList.html
src/main/resources/templates/post/postList.html
src/main/resources/templates/post/postListFragment.html
src/main/resources/templates/post/postSearchList.html

- [#188 ] 
- [#190 ] 
- [#191 ] 에 관한 내용입니다.
<br>
- CSS로 찜 버튼이 잘 보이게 수정했습니다.
- 추가로 게시일 문구를 삭제했습니다.
- 거래 완료 및 진행 중인 게시글 문구 더 잘보이게 수정했습니다.
- 로그인 안 한 사용자는 찜 기능을 눌렀을 시 Alert 을 뜨게 했습니다.
<br>
사진 봐주세요~~
<br>

style: 찜 버튼 잘 보이게 수정 / '게시일' 문구 삭제

---

src/main/java/piglin/swapswap/global/scheduler/Scheduler.java

- 스케쥴러 수정
<br>
- 스케쥴러에 오타 및 불필요한 부분이 있어서 수정합니다
<br>
- 간단한 수정입니다
<br>

fix : 스케쥴러 수정

---

src/main/resources/templates/post/post.html
src/main/resources/templates/post/postList.html
src/main/resources/templates/post/postSearchList.html

- [#217 ] 에 관한내용 입니다.
<br>
- 비 로그인 상태에서 찜 기능 작동 시 로그인 선택창 추가했습니다.
<br>
- 간단히 쓱 봐주세요~
<br>

feat: 비 로그인 상태에서 찜 기능 작동 시 로그인 선택창 추가

---

src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
src/main/resources/templates/post/postList.html
src/main/resources/templates/post/postSearchList.html

- [#215] 
- [#219] 에 관한 내용입니다.
<br>
- sql 문으로 공백 replace 하고 검색하도록 했습니다.
- 게시글 검색 후 전체보기 버튼 추가
<br>
- 몇줄만 바꿨으니 쓱 봐주세요~~
<br>

feat: 게시글 띄어쓰기 생략 검색기능 추가 / 게시글 검색 후 전체보기 버튼 추가

---

src/main/resources/templates/post/postSearchList.html

- [#220 ] 에 관한 내용입니다.
<br>
- html 내부에 selectedCity url에 추가해주는 부분 누락되어서 추가해줬습니다.
<br>
- 쓱 봐주세요~
<br>

fix: 게시글 지역 검색 후 More 메서드 실행 시 다른 지역 물품까지 불러오는 버그 수정

---

src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponServiceImplV1.java

- [#206] 에 관한 내용입니다.
<br>
- 쿠폰 발급 logging 을 추가했습니다.
<br>
- 로그에 더 필요한 정보, 불필요한 정보가 뭐가 있을까요??
<br>

feat: 쿠폰 발급 및 memberCoupon 등록 logging

---

src/main/java/piglin/swapswap/domain/post/controller/PostController.java
src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java

- [#206] 에 관한 내용입니다.
<br>
- post create/update Logging 추가
- 추가하면서 Security 재설정 및 컨트롤러 리팩토링 했습니다.
<br>
- 전체적으로 돌면서 리팩토링하고 있습니다!! 한번 봐주십쇼~
<br>

feat: post create/update Logging

---

src/main/resources/templates/post/postFavoriteList.html

- [#231 ] 에 관한 내용입니다.
<br>
- myFavoriteList html에서 불필요하게 추가 된 부분이 있어서 그 부분 지웠습니다!
<br>
- 버그인 만큼 빠르게 머지하겠습니다~~
<br>

fix: 내 찜 목록에서 로그인이 필요하다는 버그 수정

---

src/main/resources/static/js/nav.js

- 머지되면서 지역 선택 시 바로 검색하는 기능이 누락됐었습니다.
<br>
- 지역 선택 시 바로 검색하는 기능 재 추가
<br>
- 바로 머지하겠습니다.
<br>

fix: 머지되면서 누락된 지역검색 추가

---

src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
src/main/resources/static/css/style.css

- 알림창이 채팅방과 겹쳐보이는 현상 수정
<br>
- 알림창이 채팅방과 겹쳐보이는 현상 수정
<br>
- 네 
<br>

style : 알림창이 채팅방과 겹쳐보이는 현상 수정

---

src/main/java/piglin/swapswap/domain/notification/service/NotificationServiceImpl.java
src/main/resources/static/js/nav.js
src/main/resources/templates/common/fragments/head.html

- 개발자 도구 console 에서 오류 나던 것들 수정
<br>
- Uncaught SyntaxError: Unexpected token 'E', "EventStrea"... is …not valid JSON 라고 뜨는 오류 수정
- 로그인하지 않은 상태일때 알림 리스트를 불러오려고 시도하면 null이라 오류가 발생하는 것 수정
<br>
- 간단한겁니다!
<br>

Fix : 개발자 도구 console 에서 오류 나던 것들 수정

---

src/main/java/piglin/swapswap/domain/post/service/PostService.java
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java

- 게시글 업 테스트 코드 추가가 필요했습니다
<br>
- 게시글 업 기능에서 발생 가능한 예외들을 전부 테스트 코드에 담아줬습니다~~
<br>
- 쓱 봐주세요~
<br>

test: 게시글 업 테스트 코드 추가

---

src/main/java/piglin/swapswap/domain/bill/billfacade/BillFacade.java
src/main/java/piglin/swapswap/domain/bill/controller/BillController.java
src/main/java/piglin/swapswap/domain/bill/entity/Bill.java
src/main/java/piglin/swapswap/domain/bill/service/BillService.java
src/main/java/piglin/swapswap/domain/bill/service/BillServiceImplV1.java
src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletService.java
src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
src/main/java/piglin/swapswap/domain/deal/service/DealService.java
src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
src/main/resources/templates/deal/dealRequestDeal.html

- 거래 인수 기능 구현
<br>
-  거래 진행 상태 일 때 거래 인수 버튼 클릭 시 양쪽  인수 완료 시  임시 지갑에 있던 돈을 상대 지갑에 넣어줍니다.
- 거래 인수 상태에 따라 거래 상태 변경
<br>
- 오류가 있는 부분이나 코드 컨벤션에 어긋나는 부분 있으면 말씀해 주시면 감사하겠습니다.
<br>

Feat:  거래 인수 기능 구현

---

src/main/java/piglin/swapswap/domain/bill/billfacade/BillFacade.java
src/main/java/piglin/swapswap/domain/bill/controller/BillController.java
src/main/java/piglin/swapswap/domain/bill/service/BillServiceImplV1.java
src/main/java/piglin/swapswap/domain/billcoupon/controller/BillCouponController.java
src/main/java/piglin/swapswap/domain/billcoupon/service/BillCouponService.java
src/main/java/piglin/swapswap/domain/billcoupon/service/BillCouponServiceImplV1.java
src/main/java/piglin/swapswap/domain/billpost/dto/BillPostResponseDto.java
src/main/java/piglin/swapswap/domain/billpost/repository/BillPostQueryRepository.java
src/main/java/piglin/swapswap/domain/billpost/repository/BillPostQueryRepositoryImpl.java
src/main/java/piglin/swapswap/domain/billpost/service/BillPostService.java
src/main/java/piglin/swapswap/domain/billpost/service/BillPostServiceImplV1.java
src/main/java/piglin/swapswap/domain/daelwallet/mapper/DealWalletMapper.java
src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
src/main/java/piglin/swapswap/domain/notification/service/NotificationServiceImpl.java
src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java
src/main/java/piglin/swapswap/global/aspect/LogAspect.java
src/main/resources/static/css/style.css

- [#206] 에 관한 내용입니다.
<br>
- Bill / Deal / Wallet / Coupon 관련 로깅 추가
- BillService / BillPostService 리팩토링
- 코드 컨벤션 맞게 조정
- fix: dealDetail 조회 시 Button이 게시글 가리는 CSS 문제 해결
<br>
- 더 추가할 로그가 있나 한 번 봐주세요~
<br>

feat: Bill / Deal / Wallet / Coupon 로깅 및 코드 컨벤션 맞게 조정 및 리팩토링

---

src/main/resources/static/css/style.css
src/main/resources/templates/member/myPostList.html
src/main/resources/templates/post/postFavoriteList.html
src/main/resources/templates/post/postList.html
src/main/resources/templates/post/postSearchList.html

- [#261] 에 관한 내용입니다.
<br>
- 게시글 검색 시 검색 결과 없으면 결과 없다고 반환합니다.
- 게시글 찜 목록 조회 시 찜 한게 없으면 찜 한 게시글 없다고 반환합니다.
- 자신의 게시글 목록 조회 시 작성한게 없다면 없다고 반환합니다.
<br>
- 쓱 봐주세요~
<br>

feat: 게시글 검색 시 검색 결과 없으면 검색 결과 없다고 반환

---

src/main/resources/application-prod.yml

- prod.yml 에 몽고디비 설정을 추가했습니다.
<br>
- prod.yml 에 몽고디비 설정을 추가했습니다.
<br>
- 
<br>

Refactor: prod.yml에 MongoDB 추가

---

src/main/resources/application-local.yml
src/main/resources/application-prod.yml

- mongo, redis yml 코드 수정
<br>
- mongo, redis yml 코드 수정
<br>

Feat: mongo, redis yml 코드 수정

---

src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

- Swapswap Ver.2.0.0 배포 CI
<br>
- EC2 내에서 Logback 경로를 못찾아서 오류 수정
- MongoDB URI가 오기입 수정
<br>

HOTFIX: Swapswap Ver.2.0.0 배포 CI

---

src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

- HOTFIX: Swapswap Ver.2.0.0 배포
<br>
- [#269]
<br>

HOTFIX: Swapswap Ver.2.0.0 배포

---

src/main/resources/application.yml
src/main/resources/logback-spring.xml

- EC2에서 include 위치를 계속 못찾습니다.
<br>
- logback Include 수정, logback.xml -> logback-spring.xml 및 위치변경
<br>

fix: logback Include 수정, logback.xml -> logback-spring.xml 및 위치변경

---

src/main/resources/templates/deal/dealHistory.html

- deal 요청일자 글씨 넓이 변경
<br>
- 위와 같이 넓이가 좁아서 밑으로 내려와서 deal 요청일자 글씨 넓이 변경 하였습니다. 
<br>
- 네
<br>

Fix : deal 요청일자 글씨 넓이 변경

---

src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java

- Deal 생성 시 알림에 Null 값이 들어갔습니다.
<br>
- Deal Notification Null 값들어가는 오류 해결
<br>

fix: Deal Notification Null 값들어가는 오류 해결

---

src/test/resources/logback-test.xml

- logback 설정을 추가하면서 test 환경에서 logging이 안되는 것을 확인 할 수 있었습니다.
<br>
- test 환경 logback 추가
<br>
- 바로 머지하겠습니다
<br>

feat: test 환경 logback 추가
